buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Atualizei para uma versão um pouco mais recente que funciona melhor no GitHub
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        // Removi os links mortos (bintray e clojars) que causam erro no Gradle novo
    }
}
